safe:        true

source:      .
destination: ./_site

future:      true
lsi:         false
pygments:    true
markdown:    redcarpet
exclude:
  - scripts
  - templates

title: Journey to the Center of Hawkthorne
url: http://projecthawkthorne.com
author: Kyle Conroy
